/* scheduler.h — Generates an Execution Plan from an Execution Graph (RFC-007).
 *
 * The Scheduler is responsible for planning and coordinating execution.
 * It determines what, when, and where operations execute, and manages dependencies
 * without executing kernels itself.
 *
 * Core-public header for the `scheduler` module.
 * Symbols are prefixed `hbi_` (internal, no stability guarantee).
 */
#ifndef HB_SCHEDULER_H
#define HB_SCHEDULER_H

#include "common/common.h"
#include "device/device.h"
#include "graph/graph.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Scheduling Structs ────────────────────────────────────────────────────── */

typedef struct hbi_task hbi_task;
typedef struct hbi_execution_stage hbi_execution_stage;
typedef struct hbi_execution_plan hbi_execution_plan;
typedef struct hbi_scheduler hbi_scheduler;

/* A synchronization point (e.g. an execution barrier) */
typedef enum hbi_sync_type { HBI_SYNC_NONE = 0, HBI_SYNC_BARRIER, HBI_SYNC_EVENT } hbi_sync_type;

typedef struct hbi_sync_point {
    hbi_sync_type type;
    uint32_t sync_id;
} hbi_sync_point;

/* A task is the execution unit for the Scheduler. It maps 1:1 with an op node,
 * but contains dependency information and resource requirements. */
struct hbi_task {
    uint32_t task_id;
    const hbi_node *node; /* The underlying computation */

    uint32_t num_dependencies;
    uint32_t *dependencies; /* Array of task_ids this task depends on */

    size_t required_workspace;       /* Scratch memory needed */
    hbi_device_type required_device; /* Device type required for execution */

    uint32_t estimated_cost;  /* Cost heuristic for future scheduling */
    uint32_t execution_stage; /* Which stage this task belongs to */

    hbi_sync_point pre_sync;  /* Synchronization required before execution */
    hbi_sync_point post_sync; /* Synchronization signaled after execution */
};

/* An execution stage groups tasks that can potentially run in parallel.
 * For sequential policies, there will be one task per stage. */
struct hbi_execution_stage {
    uint32_t stage_id;
    uint32_t num_tasks;
    hbi_task **tasks;
    hbi_sync_point completion_barrier;
};

/* Resource requirements calculated across the entire plan */
typedef struct hbi_resource_requirement {
    size_t peak_workspace_bytes;
    size_t peak_temp_buffer_bytes;
    size_t persistent_buffer_bytes;
    hbi_device_capabilities required_caps;
} hbi_resource_requirement;

/* Statistics gathered during scheduling */
typedef struct hbi_schedule_statistics {
    uint32_t total_tasks;
    uint32_t dependency_depth;
    uint32_t critical_path_length;
    size_t estimated_memory_usage;
    uint32_t num_stages;
} hbi_schedule_statistics;

/* The finalized execution plan. Immutable once created. */
struct hbi_execution_plan {
    uint32_t num_tasks;
    hbi_task *tasks;

    uint32_t num_stages;
    hbi_execution_stage *stages;

    hbi_resource_requirement resources;
    hbi_schedule_statistics stats;
};

/* ── Scheduler API ─────────────────────────────────────────────────────────── */

/* Create a new scheduler instance. */
hbi_status hbi_scheduler_create(hbi_allocator *allocator, hbi_scheduler **out);

/* Destroy a scheduler instance. */
void hbi_scheduler_destroy(hbi_scheduler *scheduler);

/* Generate an execution plan from an execution graph.
 * Currently supports a sequential dependency-driven policy.
 * Validates against cycles and resource conflicts. */
hbi_status hbi_scheduler_create_plan(hbi_scheduler *scheduler, const hbi_graph *graph,
                                     hbi_execution_plan **out_plan);

/* Free an execution plan generated by the scheduler. */
void hbi_execution_plan_destroy(hbi_scheduler *scheduler, hbi_execution_plan *plan);

/* ── Module Identity ───────────────────────────────────────────────────────── */

/* Human-readable module name. Never NULL. */
const char *hbi_scheduler_name(void);

/* Compile-time self-check. Returns HBI_OK when the module is well-formed. */
hbi_status hbi_scheduler_selftest(void);

#ifdef __cplusplus
}
#endif

#endif /* HB_SCHEDULER_H */
